### ISSUE TITLE
MQ Connection Setup

### ISSUE THREAD

**Issue by 2020testuser** [triggermesh/mq-eventsource#2]
Hi,
Could you please clarify on the below? This is not an issue. Looks like I'm missing something.

1. I need to connect to remote MQ Server. Could you please let me know what changes are needed other than modifying the yaml?

2. Is the trigger mesh/mq-eventsource source code is for connecting to MQ Server that is running locally on the same machine (Windows)? 

3. For connecting to the remote MQ Server, how can I do the build of the source code? I used to update go.mod and use ko for build in my other projects. Could you please provide me some high level steps for this? Thanks in advance!
Appreciate your help!!

**Comment by sebgoa** [comment]
@2020testuser sorry we totally missed your question. Are you still looking to get this working ?

**Comment by mattray** [comment]
Hopefully this works for you: https://www.triggermesh.com/blog/stream-ibm-mq-message-data-across-any-platform-with-triggermesh
