### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by 2020testuser** [triggermesh/mq-eventsource#3]
@cab105 -
`I tried to build the branch that you created.
I'm gettng the below error. Could you please let me know how to resolve this error? If I use the latest version of github.com/ibm-messaging/mq-golang , 
I get an error in knative.dev/eventing-contrib. 
Thanks in advance!`
 
===========
`
go: downloading github.com/caarlos0/env v3.5.0+incompatible
go: downloading github.com/ibm-messaging/mq-golang v3.0.0+incompatible
go: downloading github.com/cloudevents/sdk-go v0.11.0
go: downloading knative.dev/eventing-contrib v0.8.2
go: downloading github.com/pkg/errors v0.9.1
go: downloading go.opencensus.io v0.22.2
go: downloading go.uber.org/zap v1.13.0
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading go.uber.org/multierr v1.4.0
go: downloading golang.org/x/lint v0.0.0-20191125180803-fdd1cda4f05f
go: downloading go.uber.org/atomic v1.5.1
go: downloading honnef.co/go/tools v0.0.1-2019.2.3
go: downloading go.uber.org/tools v0.0.0-20190618225709-2cfd321de3ee
go: downloading golang.org/x/tools v0.0.0-20200121042740-dbc83e6dc05e
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading github.com/ibm-messaging/mq-golang v1.0.0
go: downloading github.com/cloudevents/sdk-go v1.2.0

`
`./main.go:128:23: qObject.GetSlice undefined (type ibmmq.MQObject has no field or method GetSlice)`

**Comment by 2020testuser** [comment]
Closing as resolved by using the latest package.

**Comment by sebgoa** [comment]
I would love a PR with the modifications your did to get the build up to date, thanks.
